*TCO*::
    Total cost of ownership

*Pricing calculator*::
    estimate workloads

== Describe Azure managment and governance

TCO:

1. Define your workload
2. Adjust assumptions
3. View report

best method to estimate teh cost of migrating to the cloud while incurring
minimal cost

== Describe the Microsoft Cost Managment tool

=== What is Cost Managment

Cost Managment provides the ability to quickly check Azure resource cost, create
alerts based on resource spend, and create budgets that can be used to automate
management of resources.

Cost analysis is a subset of Cost Managment that provides a quick visual for
your Azure costs. Using cost analysis, you can quickly view the total cost in a
variety of different ways, including by billing cycle, region, resources, and so
on.

=== Cost alerts

Cost alerts provide a single location to quicly check all of the different alert
types that may show up in the Cost Management service. The three types of alrts
that may show up are:

- Budget alerts
- Credit alerts
- Department spending quota alerts

=== Budget alerts

Budget alerts notify you when spending, based on usage or cost, reaches or
exceeds the amount defined in the alrt condition of the budget. Cost Managment
budgets are createing the Azure portal or the Azure Consumption API.

In the Azure portal, budgets are defined by cost. Budgets are defined by cost or
by consumption usage when using the Azure Consumption API. Budget alrts support
both cost-based and usage-based budgets. Budget alerts are generated
automatically whenever the budget alrt conditions are met. You can view all cost
alerts in the Azure portal. Whenever an alert is generated, it appears in cost
alerts. An alert email is also sent to the people in the alert recipients list
of the budget.

=== Credit alerts

Credit alerts notify you when your Azure credit monetary commitments are
consumed. Monetary commitments are for organizations with Enterprise Agreements
(EAs). Credit alerts are generated automatically at 90% and at 100% of your
Azure credit balance. Whenever an alert is generated, it's reflected in cost
alerts, and in the email sent to the account owners.

=== Department spending quota alerts

Department spending quota alerts notify you when dpeartment spending reaches a
fixed threshold of the quota. Spending quotas are configured in the EA portal.
Whenever a threshold is met, it generates an email to department owners, and
appears in cost alerts. For example, 50 percent or 75 percent of the quota.

=== Budgets

A budget is where you set a spending limit for Azure. You can set budgets based
on a subscription, resource group, service type, or other criteria. When you set
a budget alert that shows up in the cost alert area. If configured, budget
alerts will also send an email notification that a budget alert threshold has
been triggered.

A more advanded use of budgets enables budget conditions to trigger automation
that suspends or otherwise modifies resources once the trigger condition has
occured.

== Describe the purpose of tags

As your cloud usage grows, it's increasingly important to stay organized. A good
organization strategy help you understand your cloud usage and can help you
manage costs.

One way to organize related resources is to place them in their own
subscriptions. You can also use resources groups to manage related resources.
Resource tags are another way to organize resources. Tags provide extra
information, or metadata, about your resources. This metadata is useful for:

- *Resource management*. Tags enable you to locate and act on resources that are
  associated with specific workloads, environments, business units, and owners.

- *Cost management and optimization*. Tags enable you to group resources so that
  you can report on costs, allocate internal cost centers, track budgets, and
  forecast estimated cost.

- *Operations management*. Tags enable you to group resources according to how
  critical their availability is to your business. This grouping helps you
  formulate service-level agreements (SLAs). An SLA is an uptime or performance
  guarantee between you and your users.

- *Security*. Tags enable ytou to classify data by its security level, such as
  public or confidential.

- *Governance and regulatory compliance*. Tags enable you to identify resources
  that align with governance or regulatory compliance requirements, such as IDO
  \27001. Tags can also be part of your standars enforcement efforts.

- *Workload optimization and automation*. Tags can help you visualize all of the
  resources that participate in complex deployment for example, you might tag a
  resource with its associated workload or application name and use software
  such as Azure DevOps to perform automated tasks on those resources.

=== How do I manage resource tags?

You can add, modify, or delete resource tags through Windows Powershell, The
Azure CLI, Azure Resource Manager templates, the REST API, or the Azure portal.

You can use Azure policy to enforce tagging rules and conventions. For example,
you can require that certain tags be added to new resources as they're
provisioned. You can also define rules that reapply tags that have been removed.
Resources don't inherit tags from subscriptions and resource groups, meaning
that you can apply tags at one level and not have those tags automatically show
up at different level, allowing you to create custom tagging schemas that change
depending on the level (resource, resource group, subscription, and so on).

=== An example tagging structure
A resource tag consists of a name and a value. You can assign one or more tags
to each Azure resource.

[%header, cols="1,2"]
|===
| Name        | Value

| AppName     | The name of the application that the resource is part of

| CostCenter  | The internal cost center code

| Owner       | The name of the business owner who's responsible for the
                resource

| Environment | An environment name, such as "Prod", "Dev", or "Test"

| Impact      | How important the resource is to business operations, such as
                "Mission-critical", "High-impact", or "Low-impact".
|===

Keep in mind that you don't need to enforce that a specific tag is present on
all your resources. For example, you might decide that only mission-critical
reources have the Imapact tag. All non-tagged resources would then not be
considered as mission-critical.

== Describe the purpose of Microsoft Purview

Microsoft Purview is a family of data governance, risk, and compliance solutions
that helps you get a single, unified view into your data. Microsoft Purview
brings insight about our on-premises, multicloud, and software-as-a-service data
together.

With Microsoft Purview, you can stay up-to-date on your data landscape to:

- Automated data discovery
- Sensitive dat classification
- End-to-end data lineage

Two main solution areas comprise Microsoft Purview: *risk and complieance* and
*unified data* governance.

=== Microsoft Purview risk and compliance solutions

Microsoft 365 features as a core component of the Microsoft Purview risk and
compliance solutions. Microsoft Teams, OneDrive Exchange are just some of the
Microsoft 365 services that Microsoft Purview use to help manage and monitor
your data. Microsoft Purview, by managing and monitoring your data, is able to
help your organization:

- Protect sensitive data across clouds, apps, devices.

- Identify data risks and manage regulatory compliance requirements.

- Get started with regulatory compliance.

Two main solutions areas comprise Microsoft Purview: *risk and compliance*

=== Microsoft Purview risk and compliance solutions

Mircosoft 365 features as a core component of the Microsoft Purview risk and
compliance solutions. Microsoft Teams, OneDrive, and Exchange are just some of
teh Microsoft 365 services that Microsoft Purview uses to help manage and
monitor your data. Microsoft Purview, by managing and monitoring your data, is
able to help your organization:

- Protect sensitive data across clouds, apps, and devices.

- Identidy data risk and manage regulatory compliance requirements.

- Get started with regulatory compliance.

=== Unified data governance

Microsoft Purview has orbust, unified data goverance solutions that help manage
your on-premises, multicloud, and software as a service data. Microsoft data.
Microsoft Purview's robust data governance capabilites enable you to manage your
data store in Azure, SQL and Hive databases, locally, and even in other clouds
like Amazon S3.

Microsoft Purview's unified data governance helps your organization:

- Create an up-to-date map of your entire data estate that includes data
  classifications and end-to-end lineage.

- Identify where sensitive data is stored in your estate.

- Create a secure environment for data consumers to find valuable data.

- Generate insight about how your data data is stored and used.

- Managed acces to the data in your estate securely and at scale.

== Describe the purpose of Azure Policy

Azure Polciy is a service that enables you to create, assign, and manage polices
that contorol or audit your resources. These polices enfore different rules
across your resource configuration so that those configurations stay compliant
with corporate standards.

=== How does Azure Policy define policies

Azure policy enables you to define both indidual policies of related policies,
known as initiatives. Azure Policy evaluates your resources and highlights
resources that aren't compliant with the polices you've created. Azure Policy
can alos prevent noncompliant resources from being created.

Azure Policies can be set at each level, enabling yo to set policies on a
specific resource, resource group, subscription, and so, on. Additionally, Azure
Policies are inherited, so if you set a policy at a high level, it will
automatically be applied to all of the grouping that fall within the parent. For
example, if you set an Azure Policy on a resource group, all resources created
within that resource group will automatically reveive the same policy.

Azure Policy comes with built-in policy and initiative definitions for Storage.
Networking, Compute, Security Center, and Monitoring. For example, if you define
a policy that allows only a certain size for the virtual machines (VMs) to be
used in your environment, that policy is invoked when you create a new VM and
whenever you resize existing VMs. Azure Policy also evealuates and monitors all
current VMs in your environment, including VMs that were created before the
policy was created.

In some cases, Azure Policy can automatically remediate noncompliant resources
and configurations to ensure the integrity of the state of the resources. For
example, if all resources in a certain resource gruop should be tagged with
AppName tag and a value of "SpecialOrders", Azure Policy will automatically
apply that tag if it is missing. However, you still retain full control of you
environment, if you have a specific resource that you don't want Azure Policy to
automatically fix, you can falg that resource as an exception - and the policy
won't automatically fix that resource.

Azure Policy also integrats with Azure DevOps by applying any continuous
integration and delivery pipeline policies that pertain to the pre-deployment
and post-deployment phases of you applications.

=== Whare are Azure Policy initiatives?

An Azure Policy initiative is a way of grouping related policies together. The
initiative definition contains all of the policy definition to help track your
compliance state for a larger goal.

Under this initiative, the following policy definitions are included:

- *Monitor unencrypted SQL Database in Security Center*. This policy monitors
  for unencrypted SQL databases and servers.

- *Monitor OS vulnerabilities in Security Center*. This policy monitors servers
  that don't satisfy the configured OS vulnerability baseline.

- *Monitor missing Endpoint protection in Security Center*. This policy monitors
  for servers that don't have an installed endpoint protection agent.

In fact, the Enable Monitoring in Azure Security Center intiative contains over
100 seperate policy definitions.

== Describe the purpose of resource locks

A resource lock prevents resources from being accidently deleted or changed.

Even with Azure role-based access control (Azure RBAC) policies in place,
there's still a risk that people with the right level of access could delete
critical cloud resources. Resource locks prevent resources from being deleted or
updated, depending on the type of lock. Resource locks can be applid to
individual resources, resource groups, or even an entire subscription. Resource
locks are inherited. meaning that if you place a resource lock on a resource
group, all of the resources within the resource group will also have the
resource lock applied.

=== Types of Resource Locks

There are two types of resource locks, one that prevents users from deleting and
one that prevents users form changing or deleting a resource.

- *Delete* means authorized users can still read and modify a resource, but they
  can't delete the resource.

- *ReadOnly* means authorized users can read a resource, but they can't delte or
  update the resource. Applying this lock is similar to restricting all
  authorized users to the permisions granted by the Reader role.

=== How do I manage resource locks?

You can manage resource locks from the Azure portal, Powershell, the Azure CLI,
or from an Azure Resource Manager template.

To view, add, or delete locks in the Azure portal, go to the settings action of
any resource's Settings pane in the Azure portal.

=== How do I delete or change a locked resource?

Although locking helps prevent accidental changes, you can still make changes by
following a two-step process.

To modify a locked resource, you must first remove the lock. After you remove
the lock, you can apply any action you have permissions to perform. Resources
locks apply regardless of RBAC permissions. Even if you're an owner of the
resource, you must still remove the lock before you can perform the blocked
activity.

=== Exercise - Configure a resource lock

In this exercise, you'll create a resource and configure a resource lock.
Storage accounts are one of the easiest types of resource locks to quickly see
the impact, so you'll use a storage account for this exercise.

== Describe the purpose of the Service Trust portal

The Microsoft Service Trust Portal is a portal that provides access to various
content, tools, and other resources about Microsoft security, privacy, and
compliance practices. 

The Service Trust Portal contains details about Microsoft's implementation of
controls and processes that protect our cloud services and the customer data
therein. To access some of the resources on the Service Trust Portal, you must
sign in as an authenticated user with your Microsoft cloud services account
(Microsoft Entra organization account). You'll need to review and accept the
Microsoft non-disclosure agreement for compliance materials.

=== Acessing the Service Trust Portal

The Service Trust Portal features and content are accessible from teh main menu.
The categories on the main menu are:

=== Knowledge Check

1. Q: Whow can you prevent creation of non-compient resources, without haveing
   to manually evealuate each resources?

1. A: Azure Policy

2. Q: What's the best way to prevent inadvertent deletion of a resource?

2. A: Azure resource locks

== Describe tools for interacting with Azure

To get teh most out of Azure, you need a way to interact with the Azure
environment, the management groups, subscriptions, resource gruops, resources,
and so on. Azure provides multiple tools for managing your environment,
including the:

- Azure portol
- Azure Powershell
- Azure Command Line interface (CLI)

=== What is the Azure portal?

The Azure portal is a web-based, unified console that provides an alernative to
command-lines tools. With the Azure portal, you can manage your Azure
subscription by using a graphical user interface. You can:

- Build, manage, and monitor everythin from simple web apps to complex cloud
  deployments

- Azure PowerShell

- Azure Command Line Interface (CLI)


=== What is Azure PowerShell?

Azure PowerShel is a shell with which developers, DevOps, and IT professional
can run commands called command-lets (cmdlets). These commands call the Azure
REST API to perform managment tasks in Azure. Cmdlets can be run independently
to handle one-off changes, or they may be combined to help orchestrate complex
actions such as:

- the routine setup, teardown, and maintance of a single resource or multiple
connected resources.

- The deployment of an entire infrastructure, which might contain dozens or
  hundreds of resources, from imperative code.

in addition to be available via Azure Cloud Shell, you can install and configure
Azure PowerSHell on Windows, Linux, and Mac plaforms.

=== What is the Azure CLI?

The Azure CLI is functionally equivalent to Azure PowerShell, with the primary
difference being the syntax of commands. While Azure Powerhsell uses Powershell
commands, teh Azure CLI uses Bash commands.

The Azure CLI provides teh same benefits of handling discrete tasks or
orchestrating complex operations through code. It's alos installable on Windows,
Linux, and Mac platforms, as well as through Azure Cloud Shell.


== Describe the purpose of Azure Arc

Managing hybrid and multi-cloud environments can rapidly get complicated. Azure
provides a host of tools to provision, configure, and monitore Azure resources.
What about the on-premises resources in a hybrid configuration or the cloud
resources in a multi-cloud configuration?

In utilizing Azure Resource Manager (ARM), Arc lets you extend your Azure
compliance and monitoring to you hybrid and multi-cloud configurations. Azure
Arc simplifies governance and management by delivering a consistent multi-cloud
and on-premises management platform.

Azure Arc provides a centralized, unified way to:

- Manage your entire environment together by projecting your existing non-Azure
  resources into ARM

- Manage multi-cloud and hybrid virtual machines, Kubernetes clusters, and
  databases as if they are running in Azure.

- User familiar Azure services and management capabilities regardless of where
  they live.

- Continue using traditional ITOps while introducing DevOps practices to support
  new cloud and native patterns in your environment.

- Configure custom locations as an abstraction layer on top of Azure Arc-enabled
  kubernetes clusters and cluster extensions.

=== What can Azure Arc do outside of Azure?

Currently, Azure Arc allows you to manage the following resource types hosted
outside of Azure:

- Server
- Kubernetes clusters
- Azure data services
- SQL Server
- Virtual machines (preview)

== Describe Azure Resource Manager and Azure ARM templates

 Azure Resource Manager (ARM) is the deployment and management service for
 Azure. It provides a management layer that enables yo to create, update, and
 delete resources in your Azure account. Anytime you do anything with your
 Azure resources, ARM is involved.

 When a user sends a request from any of the Azure tools, APIs, or SDKs, ARM
 receives the request. the, ARM sends the request to the Azure service which
 takes the requested action. You see consistent results and capabilities in all
 the different tools because all requests are handled through the same API.

 Azure Resource Manager benefits

 With Azure Resource Manager, you can:

 - Manage your infrastructure through declarative templates rather than scripts.
   A Resource Manager template is a JSON file that defines what you want to
   deploy to Azure.

- Deploy, manage, and monitor all the resources for your solution as a group,
  rather than handling these resources individually.

- Re-deploy your solution throughout the development life-cycle and have
  confidence your resources are deployed in a consistent state.

- Define the dependencies between resources, so they're deployed in the correct
  order.

- Apply access control to all services because RBAS is natively integrated into
  the management platform.

- Apply tags to resourcces to logically organize all the resources in you
  subsciption.

- Clarify your organization's billing by viewing costs for a group of resources
  that share the same tag.

=== Infrastructure as code

Infrastructure as code is a concept where you manage your infrastructure as
lines of code. At an introductory level, it's things like using Azure Cloud
Shell, Azure PowerSHell, or the Azure CLI to manage and configure your
resources. As you get more comfortable in the cloud, you can use the
infrastructure as code concept to manage entire deployments using repeatable
templates and configurations. ARM templates and Bicep are two examples of using
infrastructure as code with Azure Resource Manager to maintain your environment.

=== ARM templates

By using ARM templates, you can describe the resource you want to use in a
declarative JSON format. With an ARM template, the deploymoent code is verified
before any code is run. This ensures that the resources will be created and
connect correctly. The template then orchestrates the creation of those
resources in parallel. That is, if you need 50 instances of the same
resources, all 50 instances are created at the same time.

Ultimately, the developer, DevOps professional, or IT profesional needs only to
define the disired state and configuration of each resource in the ARM template,
and the template does the rest. Templates can even execute PowerShell and Bash
scripts before or after the resource has been set up.

=== Benefits of using ARM templates

ARM templates provide many benefits when planning for deploying Azure resources.
Some of those benefits include:

- *declarative syntax*. ARM templates allow you to create and deploy an entire
  Azure infrastructure declaratively. Declarative syntax means you declare what
  you want to deploy byt don't need to write teh actual programming commands and
  sequence to deplay the resources.

- *Repeatable results*. Repeatedly deploy your infrastructure throughout the
  development lifecycle and have confidence you resources are deployed in a
  consistent manner. You can use the same ARM template to deploy multiple
  dev/test environments, knowing that all the environments are the same.

- *Orchestration*. You don't have to worry about the complexities of ordering
  operations. Azure Resource Manager orchestrates the deployment of
  interdependent resources, so they're created in the correct order. When
  possible, Azure Resource Manager deploys resources in parallel, so you
  deployments finish faster than serial deployments. You deploy the template
  through one command, rather than through multiple imperative commands.

- *Modular files*. You can break your templates into smaller, reusable
  components and link them together at deployment time. You can also nest one
  template inside another template. For example, you could  create a template
  for a VM stack, and then nest that template inside of templates that deploy
  entire environments, and that VM stack will consistently be deployed in each
  of the environment templates.

- *Extensibility*. With deployment scripts, you can add PowerShell or Bash
  scripts to your templates. The deployment scripts exxtend your ability to set
  up resources during deployment. A script can be included in the template or
  stored in an external source and referenced in the template. Deployment
  scripts give you the ability to complete your end-to-end environment setup in
  a single ARM template

=== Bicep
Bicep is a language that uses declarative syntax to deploy Azure resources. A
Bicep file defines the infrastructure and configuration. Then, ARM deploys that
environment based on your Bicep file. While similar to an ARM template, which is
written in JSON, Bicep files tend to use a simpler, more concise style.

some benifits of Bicep are:

- *Support for all resource types and API verions*: Bicep immmediately supports
  all preview and GA versions for Azure services. As soon as a resource provider
  introduces new resoure types and API versions, you can use them in your Bicep
  file. You don't have to wait for tools to be updated before using the new
  services.

- *Simple syntax*. When compared to the equivalent JSON template. Bicep files
  are more concise and easier to read. Bicep requires no previous knowledge of
  programming languages. Bicep syntac is declarative and specifies which
  resourcesand recource properites you want to deploy.

- *Repeatable results*. Repeatedly deploy your infrastructure throughout the
  development lifecycle and have confidence your resources are deployed in a
  consistent manner. Bicep files are idempotent, which means you can deploy the
  same file many times and get the same resource types in the same state. You
  can develop one file that represents the desired state rather than developing
  lots of seperate files to represent updates.

- *Orchestration*. You don't have to worry about the complexities of ordering
  operations. Resource Manager orchestrates the deployment of  interdependant
  resources so they're created in the correct order. When possible, Resource
  Manager deploys resources in parrallel so your deployments finish faster than
  serial deployments. You deploy the file through one command, rather than
  through multiple imperative command.

- *Modularity*. You can break your Bicep code into manageable parts by using
  modules. The module deploys a set of related resources. Modules enable you to
  reuse code and simplify development. Add the module to a Bircep file anytime
  you need to deploy those resources.
