*TCO*::
    Total cost of ownership

*Pricing calculator*::
    estimate workloads

== Describe Azure managment and governance

TCO:

1. Define your workload
2. Adjust assumptions
3. View report

== Describe the Microsoft Cost Managment tool

=== What is Cost Managment

Cost Managment provides the ability to quickly check Azure resource cost, create
alerts based on resource spend, and create budgets that can be used to automate
management of resources.

Cost analysis is a subset of Cost Managment that provides a quick visual for
your Azure costs. Using cost analysis, you can quickly view the total cost in a
variety of different ways, including by billing cycle, region, resources, and so
on.

=== Cost alerts

Cost alerts provide a single location to quicly check all of the different alert
types that may show up in the Cost Management service. The three types of alrts
that may show up are:

- Budget alerts
- Credit alerts
- Department spending quota alerts

=== Budget alerts

Budget alerts notify you when spending, based on usage or cost, reaches or
exceeds the amount defined in the alrt condition of the budget. Cost Managment
budgets are createing the Azure portal or the Azure Consumption API.

In the Azure portal, budgets are defined by cost. Budgets are defined by cost or
by consumption usage when using the Azure Consumption API. Budget alrts support
both cost-based and usage-based budgets. Budget alerts are generated
automatically whenever the budget alrt conditions are met. You can view all cost
alerts in the Azure portal. Whenever an alert is generated, it appears in cost
alerts. An alert email is also sent to the people in the alert recipients list
of the budget.

=== Credit alerts

Credit alerts notify you when your Azure credit monetary commitments are
consumed. Monetary commitments are for organizations with Enterprise Agreements
(EAs). Credit alerts are generated automatically at 90% and at 100% of your
Azure credit balance. Whenever an alert is generated, it's reflected in cost
alerts, and in the email sent to the account owners.

=== Department spending quota alerts

Department spending quota alerts notify you when dpeartment spending reaches a
fixed threshold of the quota. Spending quotas are configured in the EA portal.
Whenever a threshold is met, it generates an email to department owners, and
appears in cost alerts. For example, 50 percent or 75 percent of the quota.

=== Budgets

A budget is where you set a spending limit for Azure. You can set budgets based
on a subscription, resource group, service type, or other criteria. When you set
a budget alert that shows up in the cost alert area. If configured, budget
alerts will also send an email notification that a budget alert threshold has
been triggered.

A more advanded use of budgets enables budget conditions to trigger automation
that suspends or otherwise modifies resources once the trigger condition has
occured.

== Describe the purpose of tags

As your cloud usage grows, it's increasingly important to stay organized. A good
organization strategy help you understand your cloud usage and can help you
manage costs.

One way to organize related resources is to place them in their own
subscriptions. You can also use resources groups to manage related resources.
Resource tags are another way to organize resources. Tags provide extra
information, or metadata, about your resources. This metadata is useful for:

- *Resource management*. Tags enable you to locate and act on resources that are
  associated with specific workloads, environments, business units, and owners.

- *Cost management and optimization*. Tags enable you to group resources so that
  you can report on costs, allocate internal cost centers, track budgets, and
  forecast estimated cost.

- *Operations management*. Tags enable you to group resources according to how
  critical their availability is to your business. This grouping helps you
  formulate service-level agreements (SLAs). An SLA is an uptime or performance
  guarantee between you and your users.

- *Security*. Tags enable ytou to classify data by its security level, such as
  public or confidential.

- *Governance and regulatory compliance*. Tags enable you to identify resources
  that align with governance or regulatory compliance requirements, such as IDO
  \27001. Tags can also be part of your standars enforcement efforts.

- *Workload optimization and automation*. Tags can help you visualize all of the
  resources that participate in complex deployment for example, you might tag a
  resource with its associated workload or application name and use software
  such as Azure DevOps to perform automated tasks on those resources.

=== How do I manage resource tags?

You can add, modify, or delete resource tags through Windows Powershell, The
Azure CLI, Azure Resource Manager templates, the REST API, or the Azure portal.

You can use Azure policy to enforce tagging rules and conventions. For example,
you can require that certain tags be added to new resources as they're
provisioned. You can also define rules that reapply tags that have been removed.
Resources don't inherit tags from subscriptions and resource groups, meaning
that you can apply tags at one level and not have those tags automatically show
up at different level, allowing you to create custom tagging schemas that change
depending on the level (resource, resource group, subscription, and so on).

=== An example tagging structure
A resource tag consists of a name and a value. You can assign one or more tags
to each Azure resource.

[%header, cols="1,2"]
|===
| Name        | Value

| AppName     | The name of the application that the resource is part of

| CostCenter  | The internal cost center code

| Owner       | The name of the business owner who's responsible for the
                resource

| Environment | An environment name, such as "Prod", "Dev", or "Test"

| Impact      | How important the resource is to business operations, such as
                "Mission-critical", "High-impact", or "Low-impact".
|===

Keep in mind that you don't need to enforce that a specific tag is present on
all your resources. For example, you might decide that only mission-critical
reources have the Imapact tag. All non-tagged resources would then not be
considered as mission-critical.
