== International organization for Standardization (ISO) / IEC 27001:2002

ISO/IEC family of standards provide a framework for policies and procedures that
include legal, physical, and technical controls involved in an organization risk
management process. ISO/IEC 27001:2022 is a security standard that formally
specifies an information Security Managment System (ISMS) that is needed to
bring information security under explicit management contorl.

Certification to ISO/IEC 27001:2022 helps organizations comply with numerous
regulatory and legal requirements that relate to information security.

ISO/IEc 27002:2022 specifiies the requirement for implementing, maintaining,
monitoring, and continually imporoving the ISMS. ISO/IEC 27002:2022 provides
guidelines and best practices for information security management; however, an
organization can't get certified against ISO/IEC 27001:2022, because it isn't a
management standard. The audit vechicle is ISO/IEC 27002: 2002, which relies on
detailed guidelines in ISO/IEC 27002:2022 for control implementation.

AN organization that defines international standards across all industries.

=== Azure and ISO/IEC 27002
Microsoft Azure, Dynamics 365, and other Microsoft online services undergo
regular independent third-party audits for ISO/IEC 27001 compliance. You can
review the Azure ISO/IEC 27001 certificate and audit report for more
information.

== NIST (National Institute of Standard and Technology)
AN organization that defines standards used by the United States government

The National Institute of Standars and Technology (NIST) promotes and maintains
measurement standars and guidance to help organizations assess risk. In response
to Executive Order 13636 on strengthening the cybersecurity of federal networks
and critical infrastructure, NIST released the Framework for improving Critical
Infrastructure Cybersecurity (FICIC) in February 2014.

The FICIC references globally recognized standards including NIST SP 800-53
found in Appendix A of the NIST's Framework for Improving Critical
Infrastructure Cybersecurity. Each control within the FICIC framework is mapped
to corresponding NIST 800-53 controls within teh FedRAMP Moderate Baseline.

== General Data Protection Regulation (GDRP)

A Euronpean policy that regulates data privacy and data protection

The European Union General Data Protection Regulation (GDRP) gives rights to
people (known in the regulation as data subjects) to manage the personal data
that has been collected by an employer or other type of agency or organization
(known as the data controller or just controller). Personal data is defined very
broadly under the GDRP gives data subjects specific rights to their personal
data; these rights include obtaining copies of personal data, requesting
corrections to it. restricting the processing of it, deleting it, or receiving
it in an electronic format so it can be moved to another controller. A formal
request by a data subject to a contorller to take an action on their personal
data is called _Data Subject Request_ or DSR.

== Other
You are charged per virtual machine (usually?)

You can MOVE a virtual machine from one subscription to another but you cannot
COPY a virtual machine from one subscription to another.

== OSI Model

[%header, cols="1,1,1,1"]
|===
| number | layer name   | explanation                        | example

| 7      | Application  | human interaction                  | DNS, DHCP, HTTPS, 
| 6      | Presentation | usable format                      | JPEG, MIDI, MPEG, TIFF
| 5      | Session      | maintains connections              | SQL, ZIP
| 4      | transport    | transmits data                     | TCP, UDP
| 3      | Network      | decides physical path data takes   | ICMP, IPv4, IPv6
| 2      | Data Link    | defines the format of data network | ARP, ATM, CDP
| 1      | Physical     | physical raw bit stream            | Bluetooth, Etherent 
|===
