== International organization for Standardization (ISO) / IEC 27001:2002

ISO/IEC family of standards provide a framework for policies and procedures that
include legal, physical, and technical controls involved in an organization risk
management process. ISO/IEC 27001:2022 is a security standard that formally
specifies an information Security Managment System (ISMS) that is needed to
bring information security under explicit management contorl.

Certification to ISO/IEC 27001:2022 helps organizations comply with numerous
regulatory and legal requirements that relate to information security.

ISO/IEc 27002:2022 specifiies the requirement for implementing, maintaining,
monitoring, and continually imporoving the ISMS. ISO/IEC 27002:2022 provides
guidelines and best practices for information security management; however, an
organization can't get certified against ISO/IEC 27001:2022, because it isn't a
management standard. The audit vechicle is ISO/IEC 27002: 2002, which relies on
detailed guidelines in ISO/IEC 27002:2022 for control implementation.

AN organization that defines international standards across all industries.

=== Azure and ISO/IEC 27002
Microsoft Azure, Dynamics 365, and other Microsoft online services undergo
regular independent third-party audits for ISO/IEC 27001 compliance. You can
review the Azure ISO/IEC 27001 certificate and audit report for more
information.

== NIST (National Institute of Standard and Technology)
AN organization that defines standards used by the United States government

The National Institute of Standars and Technology (NIST) promotes and maintains
measurement standars and guidance to help organizations assess risk. In response
to Executive Order 13636 on strengthening the cybersecurity of federal networks
and critical infrastructure, NIST released the Framework for improving Critical
Infrastructure Cybersecurity (FICIC) in February 2014.

The FICIC references globally recognized standards including NIST SP 800-53
found in Appendix A of the NIST's Framework for Improving Critical
Infrastructure Cybersecurity. Each control within the FICIC framework is mapped
to corresponding NIST 800-53 controls within teh FedRAMP Moderate Baseline.

== General Data Protection Regulation (GDRP)

A Euronpean policy that regulates data privacy and data protection

The European Union General Data Protection Regulation (GDRP) gives rights to
people (known in the regulation as data subjects) to manage the personal data
that has been collected by an employer or other type of agency or organization
(known as the data controller or just controller). Personal data is defined very
broadly under the GDRP gives data subjects specific rights to their personal
data; these rights include obtaining copies of personal data, requesting
corrections to it. restricting the processing of it, deleting it, or receiving
it in an electronic format so it can be moved to another controller. A formal
request by a data subject to a contorller to take an action on their personal
data is called _Data Subject Request_ or DSR.

== Other
You are charged per virtual machine (usually?)

You can MOVE a virtual machine from one subscription to another but you cannot
COPY a virtual machine from one subscription to another.

== OSI Model

[%header, cols="1,1,1,1"]
|===
| number | layer name   | explanation                        | example

| 7      | Application  | human interaction                  | DNS, DHCP, HTTPS, 
| 6      | Presentation | makes data in usable format        | 
| 5      | Session      | maintains connections              | 
| 4      | transport    | transmits data                     | TCP, UDP
| 3      | Network      | decides physical path data takes   | ICMP, IPv4, IPv6
| 2      | Data Link    | defines the format of data network | 
| 1      | Physical     | physical raw bit stream            |  Etherent 
|===

== Other
ExpressRoute is in Layer 3 of OSI model

Azure virtual networks provide isolation and segmentation


Isolation:: Genernance policies set by the organization.

Segmentation:: The ability to group related assets that are a part of (or
support) workload operations.

Azure API Management service is a way to create and manage Customer API backend
services.

resource location and resource usage effect Azure costs.

Use Azure PRcing calculator to extimate the monthly cost.

You can Deallocate or shutdown (NOT STOP) a virtual machine when it is not
needed.


*Azure Reservations* offer discounted prices on certain Azure services. up to 72
percent compared to pay-as-you-go services.

Azure Policy can help you implement MFA.

Azure policy enable you to define both individual policies and groups of
relatied policies called initiatives. Azure policy evaluates your resources and
highlights resources that are not compliant with the policies you created. 

The Azure CLI and Azure powershell can be used to manage Azure environment

Azure Arc simplifies governance and management by delivering a consistent
multicoud and on-premises management platform.

Azure Advisor evaluates resources and makes recommendations to help improve
reliability, security, and performance, achieve operation excellence, and reduce
costs.

Azure Monitor is a platform that collects metric and logging data, such as CPU
percentages, The data can be used to trigger autoscaling.

Azure Service Health notifies you of Azure related service issues, such as
region-wide downtime.

Compute and storage are provided by all cloud providers.

agility means that you can deploy and configure cloud-based resources quickly as
app requirements change.

PaaS doesn't deal with operating systems.

SaaS is software that is centrally hosted and managed for you and your users or
customers. Usually, one version of the application is used for all customers,
and it is #licensed through a monthly or annual subscriptoin#.

Azure Archive store allows you to store data offline.

You can use NFS, and SMB  to access Azure file shares.

Conditional Access is a feature that Microsoft Entra uses to allow or deny
access to resources based on identity signals, such as the device being used.

RBAC Is applied to the scope

Agility means that you can deploy and configure cloud-based resources quickly as
app requirements change.

Subscriptions may be grouped into management groups.

SQL databases and virtual machines make use of availability zones

Virtual machine scale sets are an Azure compute resource that you can use to
deploy and manage and scale a set of identical virtual machines

service endpoints are used to expose Azure services to a virtual network,
providing communication between teh two.

network security groups (NSGs) allow you configure inbound and outbound rules
for virtual networks and virtual machines.

Peering allows you to connect virtual networks together.

The TCO Calculator helps you estimate the cost saving over time of operating a
solution in Azure compared to operating in an on-premises datacenter.

Azure COst Management allows you to create and manage cost and usage budgets by
monitoring resource demand trneds, consumption rates, and cost patterns. It also
allows you to use historical data to generate reports and forecast future usage
and expenitures.

Resources tags can be used to group billing data and categorize cost by runtime
environment, such as billing usage for virtual machines running in a production
environment.

Azure Cost Management + Billing can create and manage budget and generate
historical reports and forecast future usage.

Azure Reservations offers discounted prices as apposed to pay-as-you-go.

Azure are allows you manage servers across third party cloud platforms and
on-premises environments

Data Policy in the Microsoft Purview governance portal allows you to manage
access to data sources and datasets.

ExpressRoute and Azure VPN Gateway are two services that you can use to connect
an on-pemises network to Azure.

Azure Applications Insights is a feature of Azure Monitor that allows you to
monitor running applications, automatically detect performace anomalies, and use
built-in analytic tools to see what users do on an app.

ended at https://youtu.be/C6RFbx1STUk?si=qNlYj3eQSwWhRhdV&t=12344[3:25]


== Need to review
Microsoft purciew
Describe Azure management and governance
Azure Application Insights
