== practice test

Q::
Which resource can you use to manage access, policies, and compliance across
multiple subscriptions?

A::
Managment groups

breakdown::
Managment groups can be used in environments that have multiple subscriptions to
streamline the application of governance conditions.

Resource groups can be used to organize Azure resrources.

Administrative units are used to delegate the administratoin of Azure AD
resources, such as users and gruoops.

++++
<hr>
++++

Q:: 
you need to allow resources on two different Azure virtual networking to
communicate with each other. what should you configure

A::
peering

breakdown::
You can link virtual networks together by using network peering. Peering enables
resources in each virtual network to communicate with each other.

++++
<hr>
++++

Q:: 
What can you use to conect Azure resources, such as Azure SQL databases, to an
Azure virtual network

A::
service endpoints

breakdown::
Service endpoints are used to expose Azure services to a virtual network,
providing communication between two. ExpressRoute is used to connect an
on-premises network to Azure. NSGs allows you to configure inbound and outboud
rules for virual networks and machines. Peering allowsyou to connect virtual
network together

++++
<hr>
++++

Q::
Which storage service offers fully managed file shares in the cloud that are
accesible by using Service Message Blocks (SMB) protocol.

A::
Azure files

breakdown::
Azure Files offers fully managed file shares in the cloud with shares that are
accessible by using Server Message Block (SMB) protocol. Mounting Azure file
share is just like connecting to shares on a local network.

++++
<hr>
++++

Q::
What can you use to allow a user to manage all the resources in a resource
group?

A::
Azure role-based access controll (RBAC)

breakdown::
Azure RBAC allows you to assign a set of permissions to a user or group.
Resource tags are used to locate and act on resources associated with specific
workloads, environments, business units, and owners. Resource locks prevent the
accidental change or deletion of a resource. Key Vaut is a centralized cloud
service for storing application in a single, central location.

++++
<hr>
++++

Q::
To which object or level is an Azure role-based access control (RBAC) role
applied?

A::
scope

breakdown::

An Azure RBAC role is applied to a scope, which is a resource or set of
resources that the access applies to. Resource locks prevent the accidental
cahnge or deletion of a resource. Resource tags are used to locate and act on
resource associated with specific workloads, environments, business units, and
owners. Polices enforce different rules accros resource configurations so that
the configurations stay compliant with corporate standards.

++++
<hr>
++++

Q::
What is high availability in a public cloud environment dependent on?

A::
the service-level agreement (SLA) the you choose.

++++
<hr>
++++

Q::
In which two deploymen models are customers responsible fro managing systems
that host applications? 

A::
Infrastructure as a service (IaaS), and on-premises

++++
<hr>
++++

Q::
What uses the infrastructure as a service (Iaas) cloud service model?

A::
Azure virtual machines

breakdown::

Azure Virual machiens is an Iaas offering. The customer is responsible for the
configuration of the virtual machine as well as all operating system
configurations. Azure App Services and Azure Cosmos DB are PaaS offering.
Microsoft Office is a SaaS offering.

++++
<hr>
++++

Q::
Which two factors affect Azure costs? Each correct answer presents a complete
solution.

A::
resouce locatoins, and resource usage

breakdown::
Usage meters, such as CPU time, disk size, and write operations, are used to
calculate your bill for an Azure resource. Deleting or deallocating a resource
means that you will no longer be billed for it. Different regions can have
different associated prices. Resources cost the same no matter the time of day
or the day of the week.

++++
<hr>
++++

Q::
you plan to builda new solution in Auzre that will use platform as a service
(PaaS) products. What should you use to estimate the monthly cost?

A::
Azure pricing calculator

breakdown::
The Azure Pricing calculator allows you to estimate and configure according to
your specific requirements. You will then receive a consolidated estimated price
and a detailed breakdown of the cost associated with each resource you added to
your solution.

++++
<hr>
++++

Q::
You need to recomend a solution for Azure Virtual machine deployments. The
solution must enforce company standars on the virtual machiens. What should you
include in teh recommendation?

A::
Azure Poliy

breakdown::
Azure policies allow you to enforce company standards on new virtual machines
when combined with Azure VM Image builder and Azure Compute Gallery. By using
Azure Policy and role-based access control RBAC assignments, enterprises can
enforce standards on Azure resources. But on virtual machines, these mechanisms
only affect the control plane or the route to the virtual machine.

++++
<hr>
++++

Q::
What can you use to define the resources you want to provision in a declarative
JSON format?

A::
Azure Resource Manager (ARM) templates

++++
<hr>
++++

Q::
Which managment layer accepts requests from any Azure tool or API and enables
you to create, update, and delete resources in an Azure account?

A::
Azure Resource Manager (ARM)

++++
<hr>
++++

Q::
What should you use to access Azure Cloud shell

A::
a web browser

++++
<hr>
++++

Q::
What can you use to create resources in Azure and includes a validation step to
ensure all resources are created in a specific order based on dependencies, in
parallel and idempotent

A::
Azure Resource Manager (ARM) templates

breakdowm::
ARM templates define an application's infrastructure requirements for a
repeatable deployment that is done in a consistent manner. A validation step
ensures that all resources can be created in the proper order based on
dependencies, in parallel and idempotent.

++++
<hr>
++++

Q::
You need to review the root cause analysis (RCA) report for a service outage
that occured last week. Where should you look for the report?

A::
Azure Service Health

breakdown::
AFter and outage, Service Health provides official incident reports called root
cause analysis (RCA), which you can share with stakeholders.

++++
<hr>
++++

Q::
You need to be notified when there are new recommendations for reducing Azure
costs. Which tool should you use?

A::
Azure advisor

breakdown::
Azure advisor evaluates Azure resources and makes recommendations to help
improve reliability, security, and performance, achieve operational
excellence, and reduce costs.

++++
<hr>
++++

Q::
What should  you proactively review and act on to avoid interruptions, such as
service retirements and breaking changes?

A::
health advisories

breakdown::
Health advisories are issues that require you take proactive action to avoid
service interruptions, such as service retirements and breaking changes. Service
issues are problems such as outages that require immediate actions.

++++
<hr>
++++

Q::
Which Azure service can generate an alert if virtual machine utilization is over
80% for five minutes?

A::
Azure Monitor

breakdown::
Azure monitor is a plaform for collecting, analizing, and alerting based on
metrics. Azure Monitor can log data from an entire Azure and on-premises
environment.

++++
<hr>
++++

Q::
What can you use to find information about planned maintenance for Azure
services that are critical to your organization?

A::
Azure Service Health

breakdown::
You can drill down to the affected services, regions, and details to show how an
event will affect you and what you must do. Most of these events occur without
any impact to you and will not be show. In a rare case that a reboot is
required, Service health allows you to choose when to perform the maintenance to
minimze the downtime.

++++
<hr>
++++

Q::
Which feature in the Microsoft Purview governance portal should you use to
manage access to data sources and datasets?

A::
Data Policy

breakdown::
Data Catalog -> this enables data discovery +
Data sharing -> This shares data within and between organizations +
Data Estate Insights -> This accesses data estate health +
Data Policy -> This governs access to data +

== Notes

=== Saas vs Paas vs Iaas

=== on-premises
you do everything

==== IaaS
- you do everything but you're not repsponsible for host, physical network,
  or datacenter

- vm's (virtual machines)

- vmss's (virtual machine scale sets)

==== Paas
- not repsponsible for host, physical network, or datacenter

- partially responsible for network contorls, applications, and identity and
  directory infrastructures

-  Azure Container Instances (ACI)

- Azure kubernetes Services (AKS)

- app services

- Azure Functions

- Logic apps

==== Saas
- not repsponsible for host, physical network,  datacenter, operating
  system, network controls, and applications

- partially responsible for identity and directory infastructure

- Microsoft 365


=== Azure Service health vs Azure Monitor (notifications)
- *Azure Health* notifies you when service issues, planned maintenance, or other changes may
  affect the Azure services and regions you use

- *Azure Health* notifies you about specific services

== Regions
something like east US / west US. About 100 miles apart-ish.

== Environments
Their are, china sets of regions, commercial sets of regions and
U.S. government sets of regions. Basically there are issolated sets of regions.
Every set of regions has different requirments. Different physicall facilities,
different logically, different networks, different identities providers, etc.


== Services that use pairing
- storage
- keyvaut

some services are zone redundant, meaning it spans availability zones. Other
services are zonal, meaning they will be created with a specific availablity. if
you just set a number for a public ip's availability zone then it is
zone-redundant. virtual machines are zonal and there is no option to be zone
redundant

Q::
I want to deploy a service and I want to make sure my service can survive the
failure of a data center.

A::
availability zone

== Loical components (resources)

Azure AD authentication protocols:

- OIDC
- SAML
- WS-FED
- OAUTH2

Authentication can be something I know, have or am.

