== Describe Azure storage Devices

=== Azure Migrate
Azure Migrate is a service that helps you migrate from an on-premises
environment to the cloud. Azure Migrate 

provides:

- *Unified migration platform*: A single port to start run, and track your
  migration to Azure

- *Range of tools*: A range of tools for assessment and migration. Azure Migrate
  tools include Azuure Migrate:Discovery and assessment and Azure
  Migrate:Server Migrate. Azure Migrate also inegrates with other Azure services
  and tools, and with independent software vendor (ISV) offering.

- *Assessment and migration*: In the Azure Migrate hub, you can access and
  migrate your on-premises infrastructure to Azure.

=== Integrated tools
In addition to working with tools from ISVs, the Azure Migrate hub also includes
the following tools to help with migration:

- *Azure Migrate: Disovery and assessment*. Discover and assess on-premises
  servers running VMWare, Hyper-V, and physical servers in preparation for
  migration to Azure.

- *Azure Migrate: Server Migration*. Migrate VMware VMs, Hyper-V VMs, physical servers,
  other virtualized servers, and public cloud VMs to Azure.

- *Data Migration Assistant*. Data Migration Assistant is a stand-alone tool to
  assess SQL Servers. It helps pinpoint potential problems blocking migration.
  It identifies unsupported features, new features that can benifit you after
  migration, and the right path for database migration.

- *Azure App Service migration assistant*. Azure App Service migration assistant
  is a standalone tool to assess on-premises websites for migration to Azure App
  Service. Use Migration Assistant to migrate .NET and PHP web apps to Azure.

- *Azure Data Box*. Use Azure Data Box products to move large amounts of offline
  data to Azure

=== Azure Data Box
Azure Data Box is a physical migration service that help transfer large amounts
of data in a quick inexpensive, and reliable way. The secure data transfer is
accelerated by shipping you a proprietary Data Box storage device that has a
maximum usable storage copacity of 80 terabytes. The Data Box is transported to
and from you datacenter via a regional carrier. A rugged case protects and
secures the Data Box from damage during transit.

You can order the Data Box device via the Azureportal to import or export data
from Azure. Once the device is received, you can quickly set it up using the
local web UI and connect it to your network. Once you're finished transferring
the data (either into or out of Azure), simply return the Data Box. If you're
transferrring data into Azure, the data is automattically uploaded once
Microsoft receives the Data Box back. The entire process is tracked end-to-end
by the Data Box service in the Azure portal.

==== Use cases
Data Box is ideally suited to transfer dat sizes larger than 40 TBs in scenarios
with no to limited network connectivity. The data movement can be on-time,
periodic, or an initial bulk transfer followed by periodic transfers.

Here are the various scenarios where Data Box can be used to import data to
Azure.

- Onetime migration - when a large amount of on-pemises data is moved to Azure.

- Moving a media library from offline tapes into Azure to create an online media
  library.

- Migrating you VM farm, SQL server, and applications to Azure.

- Moving historical data to Azure for in-depth analysis and reporting using
  HDInsight

- Periodic uploads - when large amount of data is generated periodically and
  needs to be moved to Azure.

  Here are the various scenarios where Data Box can be used to export data from
  Azure:

  - Disaster recovery - when a copy of the data from Azure is restored to an
    on-premises network. In a typical disaster recovery scenario, a large amount
    of Azure data is exported to a Data Box. Microsoft then ships this Data Box,
    and the data is restored on your premises in a short time.

- Security reuirements - when you need to be able to export data out of Azure
  due to government or security requirements

- Migrate back to on-premises or to another cloud service provider - when you
  want to move all the data back to on-premises, or to another cloud service
  provider, export dat via Data Box to migrate the workloads.

Once the data from your import order is uploaded to Azure, the disks on the
device are wiped clean in accordance with NIST 800-88r1 standards. For export
order, the disks are erased once the device reaches the Azure datacenter.

== Identify Azure file movement options
=== AzCopy

AzCopy is a command-line utility that you can use to copy blobs or files to or
from your storage account. With AzCopy, you can upload files, download files,
copy files between storage accounts, and even synchonize files. AzCopy can even
be configured to work with other cloud providers to help move files back and
forth between clouds.

IMPORTNAT: Synchonizing blobs or files with AzCopy is one-Direction
           synchronization. When you synchronize, you designated the source and
           destination, and AzCopy will copy files or blobs in that direction.
           It doesn't synchronize bidirectionally based on timestamps or other
           metadata.

=== Azure Storage Explorer

Azure Storage Explorer is a standalone app that provides a graphical interface
to manage files and blobs in your Azure Storage Account. It work on Windows,
macOS, and Linux operating systems and uses AzCopy on the backend to perform all
the file and blob managment tasks. With storage Explorer, you can upload to
Azure, download from Azure, or move between storage accounts.

=== Azure File Sync

Azure File Sync is a tool that lets you centralize your file shares in Azure
Files and keep the flexability, performance and  compatibility of a Windows file
server. It's almost like turning your Windows file server into a miniture
content delivery network. Once you install Azure File Sync on you local Windows
server, it will automatically stay bi-directionally synced with your files in
Azure.

With Azure File Sync, you can:

- Use any protocol that's available on Windows Server to access your data
  locally, including SMB, NFS, and FTPS.

- Have as many caches as you need across the world.

- Replace a failed local server by installing Azure File Sync on a new server in
  the same datacenter.

- Configure cloud tiering so the most frequently accessed files are replaced
  locally, while infrequently accessed files are kept in the cloud until
  requested.

== Describe Azure directory services

- Microsoft Entra ID enable you to access Microsoft cloud applicatoins and ones
  you develop.

- Entra ID can also help maintain on-premises Active directory deployment

- provide iddentity and accent managemnt service

- control the identity accounts

- available globally

- on-premesis doesn't monitor sign attempts

- can help detect suspicious sign-in attempts at no extra cost

=== Who uses Microsoft Entra Id

- *IT administrators*
- *App developers*. (such as SSO functionallity)
- *Users*. maintance self service password reset
- *Online service subscribers*. Microsoft products and stuff[,W]

=== What does Microsoft Entra ID do

- *Authentication*
    * identify access to applications and resources
    * self-service password reset
    * multifactor authentication
    * custom list of banned passwords
    * smart lockout services

- *Signle sign-on (SSO)*
    * one username and password multiple applications
    * a sinlgle identity is tied to a user
    * access modifications are tied to identity

- *Application managment*
    * cloud and on-premises apps
    * has Proxy, SaaS apps, My Apps portal

- *Device managment*
    * supports the registration of devices

    * devices can managed through tools like Microsoft Intune

    * allows device based conditional access policies to restrict attempts to
      only those comming from known devices, regardless of the requesting user
      account

=== Can I connect my on-premiss active directory (AD) with Microsoft Entra ID?

yes, if you connect Active Directory with Microsoft Id, enabling consistent
identity 

NOTE: I think it would have one identity set

if you don't conect them, you would have to maintain two identity sets.

you can connnect them with microsoct Entra Connect.

Microsoft Entra Connect synchronizes user identities between on-premises Active
Directory and Microsoft Entra ID. It synchronizeds changes between both identity
systems, so you can can use features like SSO, mutifactor authentication, and
self-service password reset under both systems.

=== What is Microsoft Enrta Domain Services?
- provides managed servces such as domain join, group policy, lightweight
  directory access protocol (LDAP), and kerberos/NTLM authentication. 

- no need to deplay, manage, and patch domain controllers (DCs) in the cloud.

A Entra Domain Services managed domain lets you run legacy applications in the
cloud that can't use modern authentication methods, or where you don't want
directory lookups to always go back to an on-premises AD DS environment. You can
lift and shift those legacy applications from your on-premises environment into
a managment domain, without needing to manage the AD DS environment in the
cloud.

Entra Domain Services Integrates with your existing Entra tenant. This
integration lets users sign into services and applications connected to the
managed domain using their existing credentials. You can also use existing
groups and user accounts to secure access to resources. These features provide a
smoother lift and shift of on-premises resources to Azure.

=== How does Microsoft Entra Domain Services work

When you define a Microsoft Entra Domain Service managed domain, you define a
unique namespace. This namespace is the domain name. Two WIndows Server domain
controllers are then deployed into your selected Azure region. This deployment
of DCs is known as a replica set.

You don't need to manage, configure, or update these DCs. The Azure platform
handles the DCs as part fo the managed domain, including backups and ancryption
at reset using Azure Disk Encryption.

=== Is information synchronized?

A managed domain is configured to perform a one-way synhronization from
Microsoft Entra Id to Microsoft Entra Domain Services. You can create resources
directly in the managed domain, but they aren't synchronized back to Microsoft
Entra ID. In a hybrid environment with an on-premises AD DS environment,
Microsoft Entra Connect synchronized identity with Microsoft Entra ID, which is
then synchronized to the managed domain.

Applications, services, and VMs in Azure that connect to the managed domain can
then use common Microsoft Entra Domain Service features such as domain join,
group policy, LDAP, and Kerberos/NTLM authentication.

= Describe Azure authentication methods

some authentication methods Azure supports:
- standard passwords
- single sign-on (SSO)
- multifactor authentication (MFA)
- passwordless

- new authentication solutions provides both security and convenience?

=== What's single sign-on?
- sign in once and use those credentials accross multiple resources and
  applications from different prociders

For SSO to work, the different applications and providers must trust the initial
authenticator.

=== What's multifactor authentication?

Multifactor authentication is the process of prompting a user for an extra form
(or factor) of identification during the sign in process.

Multifactor authentication provides additional security for your identities by
requiring two or more elements to fully authenticate. These elements fall into
three categories:

- Something the user knows - this might be a challenge question

- something the user has - this might be a code that's sent to the user's mobile
  phone

- something the user is - this is typically some sort of biometric property,
  such as fingerprint or face scan.

=== What's Microsoft Entra multifactor authentication

- provides mutlifactor authentication capabilities.

- enables users to choose an additional form of authentication during sign-in
  such as a phone call or mobile app notification

=== What's passwordless authentication?

Passwordless authentication needs to be set up on a device before it can work.
For example, your computer is something you have. Once it's been registered or
enrolled, Azure now knows that it's associated with you. Now that the computer
is known, once you provide something you know or are (such as PIN or
fingerprint), you can be authenticated without using a password.

Microsoft glonal Azure and Azure Government offer the following passwordless
authentication options.

- Windows hello for business

- Microsoft Authenticator app

- FID02 security keys

== Windows Hello for Business

Windows Hello for Business is ideal for information workers that have their own
designated Windows PC. The biometric and PIN credentials are directly tied to
the user's PC, which prevents acces from anyone other than the owner. With
public key infrastructure (PKI) integration and built-in support for single
sign-on (SSO), Windows Hello for Business provides a convenient method for
seamlessly accessing corporate resources on-premises and in the cloud.

two factor authentication

=== FIDO2 security keys

The FIDO (Fast IDentity Online) Alliance helps to promote open authentication
standards and reduce the use of passowrds as a form of authentication. FIDO2 is
the latest standard that incorportate the web authentication (WebAuthn)
standard.

FIDO2 security keys are an unphishable standards-based passwordless
authentication method that can come in any form factor. Fast Identity Online
(FIDO) is an open standard for passwordless authentication. FIDO allows users
and organizations to leverage the standard to sign-in to their resources without
a username or password by using an external security key or a platform key built
into a device.

Users can register and then select a FIDO2 security key at the sign-in interface
as their main means of authentication. These FIDO2 security keys are typically
USB devices, but could also use Bluetooth or NFC. With a hardware device that
handles the authentication, the security of an account is increased as there's
no password that could be exposed or guessed.

== Describe Azure external identities

*Entra External ID* refers to all the ways you can securely interact with users
outside of your organization. External identities may soud similar to
single-sign-on. With External Identities, external users can "bring their own
identities". Whether tehy have a corporate or government-issued digital
identity, or an unmanaged social identity like Google or Facebook, they can use
their own credentials to sign in. The external user's identity provider manages
their identity, and you manage access to your apps with Microsoft EntraID or
Azure AD B2C to keep your resources protected.

The following capabilities make up External identities:

- *Business to business (B2B) collaboration* - Collaborate with external users
  by letting them user their preferred identity to sign-in to your Microsoft
  applications or other enterprise applications (SaaS apps, customer-developed
  apps, etc). B2B collaboration users are represented in your directory,
  typically as guest users.

- *B2B direct connect* - Establish a mutual, two-way trust with another
  Microsoft Entra organization for seamless collaboration. B2B direct conncet
  currently supports Teams shared channels, enabling external users to access
  your resoureces form within their home instances of Team. B2B direct connect
  users aren't represented in your directory, but they're visible form within
  the Teams shared channel and can be monitored in Teams admin center reports.

- *Microsoft Entra business to customer (B2C)* - Publish modern SaaS apps or
  custom-developed apps (excluding Microsoft apps) to consumers and customers,
  while using Azure AD B2C for identity and access managment.

you can use a combinatino of these capabilities.

Wtih B2B you can easilty ensure that the guest users have appropriate access.
You can ask the guests themselves or a decision maker to participate in an
access review and recertify (or attest) to the guests' access. The reviewers can
give their input on each user's need for continued access, based on suggestions
from Microsoft Entra ID. When an access review is finished, you can then make
changes and remove access for guests who no longer need it.

== Descibe Azure conditional access

Conditional Access is a tool that Microsoft Entra ID uses to allow (or deny)
access to resources based on identity signals. These signals include who the
user is, where the user is, where the user is, and what device the user is
requesting access from.

Conditional Access helps IT administrators:

- Empower users to be productive wherever and whenever
- protect the organization's assets

Conditional Access also provides a more granular multifactor authentication
experience for users. For example, a user might not be challenged for a seconds
authentication factor if they're at a known location. However, they might be
challenged for a second authentication factor if their sign-in signals are
unusual or they're at an unexpected location.

During sign-in, Conditional Access collects signals form the user, makes
decisions based on those signals, and then enforces that decision by allowing or
denying the access request or challenging for multifactor authenticatoin
response.


=== When can I user Conditional Access?

Conditional Access is useful when you need to:

- Require multifaccator authentication (MFA) to access an application depending
  on the requester's role, location, or network.

- Require access to services only through approved client applications.

- Require user to access your application only from managed devices. A managed
  device is a device that meets your standars for security and compliance.

- Block access from untrusted sources, such as access from unkown or unexpected
  locations

== Describe Azure role-based access control (RBAC)

*principle of least privilege*::
    only grant access up to the level needed to complete a task

principle of least privilege would become tedious. Instead of this Azure enables
you to control access through Azure role-based access control.

Azure provides built-in roles that descibe common access rules for cloud
resources. You can alos define your own roles. Each role has an associated set
of access permisions that relate to that role. When you assign individual or
groups to one or more roles, they receive all the associated access permisions.

== How is role-based access control applied to resources?

Role-based access control is applied to a scope, which is a resource or set of
resource that this access applies to.

Scopes include:

- A management group (a collection of multiple subscriptoins).
- A single subscription.
- A resource group.
- A single resource

Observers, users managing resources, admins, and automated processes illustrate
the kinds of users or accounts that would typically be assigned each of the
various roles.

Azure RBAC is hiearchical, in that when you grant access at a parent scope,
those permissions are inherited by all child scopes. For example:

- When you assign the Owner role to a user at the management group scope, that
  user can manage everything in all subscriptions within the managment group.

- When you assign the Reader role to a group at the subscription scope, the
  member of that group can view every resource grouop and resource within the
  subscription

=== How is Azure RBAC enfored?

Azure RBAC is enforced on any action that's initiated against an Azure resource
that passes through Azure Resource Manager. Resource Manager is a managment
service that provides a way to organize and secure your cloud resources.

you typically acces Resource Manager from the Azure portal, Azure Cloud Shell,
Azure PowerShell, and the Azure CLI. Azure RBAC doesn't enfore access
permissions at the application or data level. Application security must be
handled by your application.

Azure RBAAS uses an allow model. When you're assigned a role, Azure RBAC allows
you to perfor actions within the scope of that role. If one role assignment
grants you read permissoins to a resource grouop and a different role assignment
grants you write permissions to the same resource group, you have both read and
write permisions on the resource group.

== Descibe zero trust model

- assumes the worst case scenario and protects resources with that expectation.

Zero Trust assumes breach at the outset, and then verifies each request as
though it orginated form an uncontrolled network.

Zero Trust security model is based on these guiding principles:

- *verity explicitly* - always authenticate and authorized based oonn all
  available data points

- *Use least privilege access* - Limit user access with Just-In-Time and
  Just-Enough-Access (JIT/JEA), risk-based adaptive policies, and data
  protection

- *Assume breach* - Minimize blast radius and segment access. Verify end-to-end
  encrytion. Use analytics to get visabliity, drive threat detection, and
  improve defenses.

== Describe defense-in-depth

The objective of defense-in-depth is to protect information and prevent it from
being stolen by those who aren't authorized to access it.

A defense-in-depth strategy uses a series of mechanisms to slow the advance of
an attack that aims at acquiring unauthorized access to data.

=== Layer of defense-in-depth

You can visualize defense-in-depth as a set of layers, with the data to be
secured at the center and all the other layers functioning to protect that
central data layer.

Each layer provides protection so that if one layer is breached, a subsequent
layer is already in place to prevent further exposure.

Brief overview of the role of each layer:

- *Physcial security layer*. The first line of defense to protect computing
  hardware in the datacenter.

- *The indentity and access layer*: controls access to infrastructure and change
  control

- *The perimeter layer*: uses distibuted denial of Service (DDos) protection to
  filter large-scale attacks before they can cause denial of service for users.

- *The network layer*:. limits communication between resources through
  segmentation and access controls.

- *The compute layer*: secures access to virtual machines

- *The application layer*: helps ensure that applications are secure and free of
  security vulnerabilities.

- *The data layer* controls access to businiess and customer data that you need
  to protect

==== Physical security

==== Identity and access

- control access to infrastructuer and change control
- User single sign-one (SSO) and multifactor authentication
- Audit events and chanages

==== Perimeter
alert you when attack are happening

- user perimieter firewall to identify and alert malicious attacks against your
  network

==== Network

- Limit communication between resources
- Deny by default
- Restrict inbound internet access and limit outbound access where appropriate
- impelement secure connectivity to on-premises networks

==== Compute
- Implement endpoint protection on devices and keep systems patched and current

==== Application
- Store sensitive application secrets in a secure storage medium
- Make security design requirement for all applications

==== Data

in almost all cases, attackers are after data:

- stored in database.
- stored on disk inside virtual machines
- stored in software as a service (SaaS) applications (such as Office 365)
- Managed through cloud storage

== Descibe Microsoft Defender for Cloud
- monitors your cloud, on-premises, hybrid, and mult-clound environments

=== Protection everywhere you're deployed
in on-premises datacenters, defender may not give you a complete picture

- can automatically deploy a Log of Analytics to gather security-related data.
  For Azure machines, deployment is handled directly.

For hybrid and multi-cloud environments, Microsoft Defender plans are extended
to non Azure machines with the help of Azure Arc. Cloud security posture
managment (CSPM) features are extended to multi-cloud machines without the need
for any agents.

=== Azure-native protections

Defender for Cloud helps you detect threats across:

- Azure PaaS services - Detect threats targeting Azure Services including Azure
  App Service, Azure SQL, Azure Storage Account, and more data services. You can
  also perform anomaly detection on your Azure activity logs using the native
  integratoin with Microsoft Defender for Cloud Apps

- Azure data services - Defender for Cloud includes capabilities that help you
  automatically classify your data in Azure SQL. You can also tget assessments
  for potential vulnerabilities acess Azure SQL and Storage services, and
  recommendatinos for how to migrate them

- *Networks* - Defender for Cloud helps you limit exposure to brute force
  attacks. Buy reducing access to virtual machines ports, using the just-in-time
  VM access, you can harden your network by preventing unnecessary access. You
  can set secure access policies on selected ports, for only authorized users,
  allowed source IP address ranges or Ipaddresses, and for a limitd amount of
  time.

=== Defened your hybrid resources

In addition to defending your Azure environment, you can add Defender for cloud
capabilities to your hybrid cloud environment to protect you non-Azure servers.
To help you focus on what matters the most, you'll get customized thread
inelligence and prioritized alerts according to your specific environment.

To extend protection to on-premises machines, deploy Azure Arc and enable
Defender for Cloud's enhanced security features.

=== Defend resources running on other clouds
- such as AWS and GCP

For example, if you've connected an Amazon Web Service (AWS) account to an Azure
subscription, you can enable any of these protections

- Defender for Cloud's CSPM features extend to your AWS resoureces. This
  agentless plan assess you AWS resources according to AWS-specific security
  recommendations, and includes the results in the secure score. The resources
  will also be assessed for compliance with built-in standards specific to AWS
  (AWS, CIS, AWS PCI DSS, and AWS Foundational Security Best Practices).
  Defender for Cloud's asset inventory page is a multi-cloud enabled feature
  helping you manage your AWS resources alongside you Azure resources.

- Microsoft Defender for Containers extends its container threat detection and
  advanced defense to you Amazon EKS linuc clusters.

=== Assess, Secure and Defend

fills these needs:

- continously assess - Know your security posture. Identify and track
  vulnerabilities.

- Secure - Harden resources and services with Azure Security Benchmark

- Defend - Detect and resolve threats to resources, workloads, and services

==== Continuosly assess

continously assesses your environment.

=== Secure

plocies in Defender for Cloud are built on top of Azure Policy Controls.

The list of recommendations is enabled and supported by the Azure Security
Benchmark. This Microsoft-authored, Azure-specific, benchmark provides a set of
guidelines for security and compliance best priactices based on common
compliance frameworks.

To help you understand how important each recomendation is to your overall
security posture, Defender for Cloud groups the recommendations into security
controls and adds a secure score value to each control. The secure score gives
you an at-a-glance indicator fo the health of you security posture, while the
controls give you a working list of things to consider to improve your security
score and your overall security posture.

=== Defend

==== Security alerts

When defender for Cloud detects a threat in any area of your environment, it
generates a security alert. Security alerts:

- Descibe details of the affected resources.
- Suggest remediation steps
- Provide, in some cases, an option to trigger a logic app in response

Whether an alert is generated by Defender for Cloud or received by Defender for
Cloud from an integrated security product, you can export it. Defend for Cloud's
thread protection includes fusion kill-chain analysis, which automatically
correlates alerts in you environment based on cyber kill-chain analysis, to help
you better understand the full story of an attack campaign, where it started,
and what kind of impact it had on your resources.

=== Advanced threat protection

Defender for cloud provides advances threat protection features for many of you
deployed resources, including virtual machines, SQL databases, containers, web
applications, and you network. Protections include securing the management ports
of your VMs with just-in-time access, and adaptive application controls to
create allowlists for what apps should and shouldn't run on your machines.
