== Describe teh purpose of Azure Advisor

Azure Advisor evaluates your Azure resources and makes recommenations to help
improve reliability, security, and performance, achieve operational excellence,
and reduce costs. Azure Advisor is designed to help you save time on cloud
optimization. The recommendation service includes suggested actions you can take
right awawy, postpone or dismiss.

The recomendations are available via the Azure portal and the API, and you can
set up notifications to alert you to new recommendations.

recommendatoins are divided into five categories:

- *Reliability*. is used to ensure and improve the continuity of your
  business-critical applications.

- *Security*. is used to detect threats and vulnerabilities that might lead to
  security breaches.

- *Performance*. is used to improve the speed of your applications.

- *Operational Excellence*. is used to help you achieve process and workflow
  efficiency, recource manageability, and deployment best practices.

== Describe Azure Service Health

Microsoft Azure provides a global cloud solution to help you manage you
infrastructure needs, reach your customers, innovate, and adapt rapidly. knowing
the status of the global Azure infrastructure and you individual resources
could seem like a daunting task. Azure Service Health helps you keep track of
Azure resource, both your specifically deployed resources and the overall status
of Azure. Azure service health does this by combining three different Azure
services:

- *Azure Status* is a broad picture of the status of Azure globally. Azure
  status informs you of service outages in Azure on the Azure Status page. The
  page is a global view of the health of all Azure services across all Azure
  regions. It's a good reference of incidents with widespread impact.

- *Service Health*. provides a narrower view of Azure services and regions. It
  focuses on the Azure service and regions you're using. This is the best place
  to look for service impacting communications about outages, planned
  maintenance activities, and other health advisories because teh authenticated
  Service Heal experience knows which services and resources you currently use.
  You can even set up Service health alerts to notify you when service issues,
  planned maintenance, or other changes may affect teh Azure services and
  regions you use.

- *Resource Health*. Is a tailored view of you actual Azre resources. It
  provides information about the health of your individual cloud resources, such
  as a specific virtual machine instance. Using Azure Monitor, you can also
  configure alerts to notify you of availability changes to your cloud
  resources.

== Describe Azure Monitor

Azure Monitor is a platform for collecting data on your resources, analyzing
that data, visualizing the information, and even acting on the results. Azure
Monitor can monitor Azure resources, your on-premises resources, and even
multi-cloud resources like virtual machines hosted with a different cloud
provider.

You can use the data to help you react to critical evens in real time, though
alerts delivered to teams viea SMS, email, and so on. Or you can use thresholds
to trigger autoscaling functionality to scale to meet the demand.

=== Azure Log Analytics

Azure Log Analytics is the tool in the Azure portal where you'll write and run
log queries on the data gathered by Azure Monitor. Log Analytics is a robust
tool that supports both simple, complex queries, and data analysis. You can
write a simple query that returns a set of records and then use geatures of Log
Analytics to sort, filter, and analyze the records. You can write and advance
query to perform statistical analysis and visualize the results in a chart to
identify a particular trend. Whether you work with the results of your queries
interactively or use them with other Azure Monitor features such as log query or
workbooks, Log Analytics is the tool that you're going to use to write and test
those queries.

=== Azure Monitor Alerts

Azure Monitor Alerts are an automated way to stay informed when Azure Monitor
detects a threshold being crossed. You set the alert conditions, the
notification actions, and tehn Azure Monitor Alerts notifies when an alert is
triggered. Depending on your configuratoin, Azure Monitor Alerts can also
attempt corrective action.

Alerts can be set up to monitor the logs and trigger on certain log events, or
they can be set to monitor metric and trigger when certain metrics are crossed.
For example, you could set a metric-based alrt up to notify you when the CPU
usage on a virtual machine exceeds 80%. Alert rules based on metrics provide
near real time alerts based on numeric values. Rules based on logs allow for
complex logic across data from multiple sources.

Azure Monitor Alerts use action groups to configure who to notify and what
action to take. An action group is simply a collection of notification and
action preferences that you associate with one or multiple alerts. Azure
Monitor, Service health, And Azure Advisor all use actions groups to notify you
when an alert has been triggered.

=== Application Insights

Application Insights, an Azure Monitor feature, monitors your web applications.
Application Insights is capable of monitoring applications that are running in
Azure, on-premises, or in a different cloud environment.

There are two ways to configure Application Insights to help monitor your
application. You can either intall an SDK in your application, or you can use
Applicatoin Insight agent. The Application Insight agent is supported in C#
\.NET, VB.NET, JavaScript, Node.js, and Python.

Once Application Insights is up and running, you can use it to monitor a broad
arary of information, such as:

- Request rates, response times, and failure rates

- Depenency rates, response times, and failure rates, to show whether external
  services are slowing down performance.

- Page views and load performance reported by users' browsers

- AJAX calls from web pages, including rates, response times, and failure rates

- User and session counts

- Performace counters from Windows or Linux server machines, such as CPU,
  memory, and network usage

Not only does Application Insights help you monitor the performance of your
application, but you can also configure it to periodically send synthetic
requests to your application, allowing you to check the status and monitor your
application even during periods of low activity
